running ["C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\lib\\windows-i686\\zsync.exe", '-o', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\editra-windows.update.new", '-k', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\editra-windows.zsync", '-i', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\editra-windows.update", '-i', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\editra-windows.update", 'http://update.renpy.org/release/renpy-6.99.11-editra-windows.zsync']
partfile does not exist
partfile does not exist
partfile does not exist
running ["C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\lib\\windows-i686\\zsync.exe", '-o', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\sdk.update.new", '-k', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\sdk.zsync", '-i', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\sdk.update", '-i', "C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\update\\sdk.update", 'http://update.renpy.org/release/renpy-6.99.11-sdk.zsync']
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
could not rename file C:\Users\MrLaban\Documents\Ren'Py\renpy-6.99.5-sdk\launcher/game/Roboto-Light.ttfR C:\Users\MrLaban\Documents\Ren'Py\renpy-6.99.5-sdk\launcher/game/Roboto-Light.ttfTraceback (most recent call last):
  File "renpy/common/00updater.rpy", line 109, in process_deferred
    process_deferred_line(l)
  File "renpy/common/00updater.rpy", line 75, in process_deferred_line
    os.unlink(fn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u"C:\\Users\\MrLaban\\Documents\\Ren'Py\\renpy-6.99.5-sdk\\launcher/game/Roboto-Light.ttf"
